<a href="https://colab.research.google.com/github/shaalu2408-pixel/python-module-5/blob/main/Python_DA_Assignment_1_Data_Analysis_using_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array Operations:

**1. Create a 1D NumPy Array:**

In [ ]:
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1 )

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


**2. Inspection and Properties:**

In [ ]:
print(temperatures_w1.shape)         #shape of the temperatures_w1 array.
print(temperatures_w1.dtype)         #data type of the temperatures_w1 array.
print(temperatures_w1.size)          #size of the temperatures_w1 array.

(7,)
float64
7


**3. Array Operations:**

In [ ]:
temp_Fahrenheit=(temperatures_w1 * 9/5) + 32
print(temp_Fahrenheit)
print(np.max(temp_Fahrenheit))                    #maximum temperatures for the week.
print(np.min(temp_Fahrenheit))                    #minmum temperatures for the week.
print(np.mean(temp_Fahrenheit))                   #mean temperatures for the week.

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
78.98
69.44
74.37714285714286


**4. Array Slicing and Indexing:**

In [ ]:
print(temp_Fahrenheit[0:3])           #temperatures for the first three days of the week.
print(temp_Fahrenheit[5:])            #temperatures for the weekend (last two days).
print( temp_Fahrenheit[2:5])          #temperatures for the middle three days of the week.

[72.5  77.54 69.44]
[76.64 71.42]
[69.44 74.12 78.98]


**5. Create a 2D Array:**

In [ ]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] ])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


**6. Inspect and Slice the 2D Array:**

In [ ]:
print(temperatures.shape)         #shape of the temperatures array.
print(temperatures.dtype)         #data type of the temperatures array.
print(temperatures.size)          #size of the temperatures array.
print(temperatures[0])            #temperatures of week 1.
print(temperatures[1])            #temperatures of week 2.
print(temperatures[0,5:])         #weekend temperatures of week 1.
print(temperatures[1,5:])         #weekend teperatures of week 2.

(2, 7)
float64
14
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
[24.8 21.9]
[22.8 20.1]


# Pandas Series:

### **1. Creating Pandas Series:**

In [ ]:
import pandas as pd
marks = [ 95, 92, 89, 85, 80 ]
custom_indices = [ 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5' ]
marks = pd.Series(marks, index = custom_indices)
marks


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

### **2. Indexing and Slicing:**

In [ ]:
marks.iloc[0]                    # integer index position to access the mark of the 1st rank student.

np.int64(95)

In [ ]:
marks.loc["Rank1":"Rank3"]      #loc accessor to retrieve the marks of the top 3 ranks.


Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [ ]:
marks.iloc[2]                     #iloc accessor to retrieve the mark of the 3rd rank student.

np.int64(89)

In [ ]:
marks[marks>90]         # boolean mask to find & retrive ranks where the marks are greater than 90.

Rank1    95
Rank2    92
dtype: int64

### **3. Manipulating Series:**

In [ ]:
marks.loc['Rank1'] = 100         #Modify the mark of the student with the 1st rank to 100.
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
marks.drop('Rank5')        #Remove the entry corresponding to the last rank from the Series.


Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [ ]:
CGPA = marks / 10            # CGPA by dividing each mark in the Series by 10.
CGPA

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64

## **Pandas DataFrame:**

### **1. Creating Pandas DataFrame:**

In [ ]:
import pandas as pd
transactions = {
   'TransactionID'   : [ 101, 102, 103, 104, 105, 106, 107, 108, 109, 110 ],
   'ProductCategory' : ['Electronics', 'Clothing', 'Electronics', 'Furniture','Clothing',
                        'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
         'Region'    : ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
                        'South', 'North' ],
        'Amount'     :  [200,150, 300, 450, 200, 250, 300, 180, 350, 400]

}
df = pd.DataFrame(transactions)

df

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

## 2. Data Exploration:

In [ ]:
print("Dataframe:\n",df)                   # DataFrame and its basic information
print("\n Head: \n",df.head())             # head
print("\n Tail: \n",df.tail())             # tail
print("\n shape: \n",df.shape)             # shape
print("\n Column Names: \n",df.columns)    # column names
print("\n Data Types: \n",df.dtypes)       # data types

Dataframe:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

 Head: 
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

 Tail: 
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7       

In [ ]:
df[['ProductCategory','Amount']]            #Display only the 'ProductCategory' and 'Amount' columns.

ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
df.iloc[:,-3:]                                        #Retrieve the last 3 columns of the DataFrame using iloc or loc

ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
df[(df["Region"]=='North') & (df["Amount"]>200)]                 #Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
df['ProductCategory'].value_counts()                        #Find the value counts for the 'ProductCategory' column.

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
df['Region'].unique()                                             #Find the unique values in the 'Region' column.

array(['North', 'South', 'East', 'West'], dtype=object)

In [ ]:
df.groupby('Region')['Amount'].mean()                            #Group by 'Region' and find the mean amount for each region.

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

**3. Manipulating the DataFrame:**

In [ ]:
df.loc[df['TransactionID']==102,'Amount']=165      #Modify the 'Amount' for the transaction with TransactionID 102 to 165.
df

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
df['Discount']= df['Amount'] / 10                    # Add a new column 'Discount' by calculating 10% of the 'Amount'.
df

TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
df.drop(8)                      #Remove the row with TransactionID 109.

TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
df.drop('Discount',axis=1)            #Delete the 'Discount' column from the DataFrame.

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400